apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: agc-ingress
  annotations:
    kubernetes.io/ingress.allow-http: 'false'
spec:
  tls:
    -
      secretName: agc-tls-credentials
  backend:
    serviceName: agc-worker
    servicePort: 8000
