apiVersion: apps/v1
kind: Deployment
metadata:
  name: scc-state
spec:
  replicas: 1
  selector:
    matchLabels:
      component: scc-state
  template:
    metadata:
      labels:
        component: scc-state
    spec:
      containers:
      - name: scc-state
        image: socketcluster/scc-state:v6.1.0
        ports:
        - containerPort: 7777
        livenessProbe:
          httpGet:
            path: /health-check
            port: 7777
          initialDelaySeconds: 15
          timeoutSeconds: 5